const skillDiemMac = [
  { name: "Võ Thánh", desc: "Bạn có thể sử dụng hoặc đánh ra lá Đỏ như [Sát]. Lá [Sát] chất ♦ bạn dùng không hạn chế cự ly." },
  { name: "Đoạn Lương", desc: "Giai đoạn hành động, bạn có thể dùng Phi Công cụ Đen như [Binh Lương Thốn Đoạn]. Nếu lượt này bạn chưa gây sát thương, bạn dùng [Binh Lương Thốn Đoạn] không hạn chế cự ly." },
  { name: "Kỳ Sách", desc: "Một lần trong giai đoạn hành động, bạn có thể dùng tất cả bài trên tay như 1 lá Công cụ phổ thông."},
  { name: "Tru Hại", desc: " Giai đoạn kết thúc của người khác, nếu lượt này họ đã gây thiệt hại, bạn có thể dùng 1 lá trên tay như [Sát] hoặc [Quá Hà Sách Kiều] đối với họ."},
  { name: "Hỏa Kế", desc: "Bạn có thể dùng lá Đỏ như [Hỏa Công]. [Hỏa Công] bạn dùng sửa thành: “lệnh mục tiêu lộ ra ngẫu nhiên 1 lá trên tay, nếu bạn tự bỏ 1 lá trên tay cùng màu với lá họ lộ, bạn gây 1 sát thương Hỏa đối với họ”."},
  { name: "Liên Hoành", desc: "Giai đoạn hành động, bạn có thể trọng chú lá ♣ hoặc dùng lá ♣ như [Thiết Tác Liên Hoàn]. Lá [Thiết Tác Liên Hoàn] bạn dùng có thể chọn thêm 1 mục tiêu."},
  { name: "Quốc Sắc", desc: "Một lần trong giai đoạn hành động, bạn có thể: 1. Dùng 1 lá ♦ như [Lạc Bất Tư Thục]; 2. Hủy 1 lá [Lạc Bất Tư Thục] trên bàn. Sau đó, bạn rút 1 lá."},
  { name: "Song Hùng", desc: "Cuối giai đoạn rút bài, bạn có thể tự bỏ 1 lá. Nếu làm vậy, cho đến hết lượt: bạn có thể dùng bài trên tay khác màu với lá đã bỏ theo cách này như [Quyết Đấu]. Giai đoạn kết thúc, bạn nhận những lá đã gây thiệt hại đối với bạn trong lượt này."},
  { name: "Loạn Kích", desc: "Giai đoạn hành động, bạn có thể dùng 2 lá trên tay cùng chất như [Vạn Tiễn Tề Phát]. [Vạn Tiễn Tề Phát] bạn dùng có thể - 1 mục tiêu."},
  { name: "Khuynh Quốc", desc: "Bạn có thể sử dụng hoặc đánh ra lá Đen trên tay như [Thiểm]."},
  { name: "Huy Vân", desc: "Bạn có thể dùng 1 lá như [Hỏa Công], sau khi kết toán lá này, bạn lệnh mục tiêu chọn Có hoặc Không thực hiện 1 mục (mỗi mục/ lần/ vòng): 1. Dùng lá vừa lộ và trọng chú tất cả bài trên tay; 2. Dùng 1 lá trên tay và trọng chú lá vừa lộ; 3. Rút 1 lá."},
  { name: "Chiến Tuyệt", desc: "Giai đoạn hành động, bạn có thể dùng tất cả bài trên tay như [Quyết Đấu]. Sau khi kết toán, bạn và người nhận thiệt hại lá [Quyết Đấu] này mỗi người rút 1 lá. Nếu bạn rút > 2 lá từ kĩ năng này trong lượt, kỹ năng này vô hiệu đến cuối giai đoạn này."},
  { name: "Niệm Ân", desc: "Bạn có thể dùng/ đánh ra 1 lá như Cơ bản tùy ý. Nếu lá chuyển hóa theo cách này không phải [Sát] thường hoặc lá này màu Đen, cho đến hết lượt: bạn nhận <<Mã Thuật>> và vô hiệu <<Niệm Ân>>."},
  { name: "Tuyệt Võ", desc: "Bạn có thể dùng lá có điểm số 2 như lá loại gây sát thương (mỗi danh bài một lần mỗi lượt). Bài trên tay bạn nhận từ người khác xem như điểm là 2."},
  { name: "Long Hồn", desc: "Bạn có thể dùng/ đánh ra tối đa 2 lá: ♥ như [Đào]; ♦ như Hỏa [Sát]; ♣ như [Thiểm]; ♠ như [Vô Giải Khả Kích]. Nếu theo cách này chuyển hóa 2 lá: Đỏ: hiệu quả hồi phục hoặc sát thương + 1; Đen: bạn hủy 1 lá của người đang có lượt."},
  { name: "Cấp Cứu", desc: "Khi cần dùng [Đào] ngoài lượt, bạn có thể dùng 1 lá Đỏ như [Đào]."},
  { name: "Mậu Diệm", desc: "Chuyển hoán kỹ Dương: Bạn có thể dùng lá Đen như [Hỏa Công], sau khi kết toán lá này, nếu lá này gây thiệt hại, bạn thu lấy tất cả những lá đã lộ trong giai đoạn này; Âm: Bạn có thể dùng lá Đen như [Hỏa Công], sau khi kết toán lá này, nếu lá này không gây thiệt hại, Mậu Diệm vô hiệu đến hết vòng."},
  { name: "Man Tự", desc: "Giai đoạn hành động 1 lần, bạn có thể dùng tất cả bài trên tay như [Nam Man Nhập Xâm]. Sau khi 1 người nhận sát thương bởi [Nam Man Nhập Xâm], bạn rút 1 lá."},
  { name: "Túc Tật", desc: "Đầu giai đoạn hành động của 1 người không đầy máu, bạn có thể dùng 1 lá Đen như [Sát], sau khi kết toán [Sát] này, nếu [Sát] này gây thiệt hại đối với họ, bạn thu lấy 1 lá của họ."},
  { name: "Phá Trúc", desc: "Giai đoạn hành động, bạn có thể dùng 1 lá trên tay như [Xuất Kỳ Bất Ý]. Nếu lá này không gây thiệt hại, Phá Trúc vô hiệu đến hết lượt."},
  { name: "Tửu Trì", desc: "Bạn có thể dùng lá ♠ trên tay như [Tửu]. Không hạn chế số lần dùng [Tửu] trong lượt."},
  { name: "Phụ Hồn", desc: "Bạn có thể sử dụng hoặc đánh ra 2 lá trên tay như [Sát]. Sau khi gây sát thương theo cách này trong giai đoạn hành động, bạn nhận <<Võ Thánh>> và <<Bào Hao>> đến hết lượt."},
  { name: "Giải Huyền", desc: "Hạn định kỹ Chuyển hoán kỹ Bạn có thể dùng lá; Dương: Đỏ như [Thuận Thủ Khiên Dương]; Âm: Đen như [Quá Hà Sách Kiều]."},
  { name: "Kỳ Tập", desc: "Bạn có thể dùng lá Đen như [Quá Hà Sách Kiều]."},
  { name: "Ủy Lâm", desc: "Mỗi lượt 1 lần, khi cần dùng [Sát] hoặc [Tửu], bạn có thể dùng 1 lá như [Sát] xem như [Tửu] và ngược lại, bài trên tay mục tiêu có cùng màu với lá này xem như [Sát] đến hết lượt."},
  { name: "Vi Ngỗ", desc: "Một lần trong giai đoạn hành động, bạn có thể dùng 1 lá Đỏ như [Thuận Thủ Khiên Dương] (không hạn chế cự ly)."},
  { name: "Liên Thảo", desc: "Đầu giai đoạn hành động, bạn có thể lệnh 1 người khác chọn 1 màu, sau đó bạn lộ tất cả bài trên tay và lần lượt dùng 1 lá trên tay cùng màu với màu họ chọn như [Quyết Đấu] đối với họ đến khi bạn hoặc họ tiến vào trạng thái hấp hối, cuối cùng bạn rút X lá (X là số sát thương bạn gây ra bởi Liên Thảo đối với họ). Nếu X = 0, bạn rút 1 lá, lượt này giới hạn trữ bài + 1 và không thể dùng [Sát]."},
  { name: "Khán Phá", desc: "Bạn có thể dùng lá Đen như [Vô Giải Khả Kích]. Người khác không thể hưởng ứng [Vô Giải Khả Kích] bạn dùng."},
  { name: "Chử Tửu", desc: "Khi cần dùng [Tửu], bạn có thể dùng ít nhất X + 1 lá như [Tửu] (X là số lần bạn đã dùng [Tửu] lượt này), sau đó nếu tất cả những lá này không phải ♣, kĩ năng này vô hiệu đến hết lượt hiện tại."},
  { name: "Sàm Nghịch", desc: "Một lần trong giai đoạn hành động, bạn có thể giao tùy ý bài trên tay cho 1 người khác, sau đó họ có thể dùng tối đa lượng bài tương đương trên tay như [Quyết Đấu]. Sau đó: - Sau khi họ gây sát thương bởi lá này: họ rút X lá; - Sau khi họ nhận sát thương bởi lá này, bạn bỏ tất cả bài trên tay. (X là số lá họ dùng như [Quyết Đấu] lần này)."},
  { name: "Tý Đạo", desc: "Giai đoạn hành động, sau khi chỉ định người khác trở thành mục tiêu dùng bài liên tiếp, nếu chưa phát động Tý Đạo trong giai đoạn này, bạn có thể dùng 1 lá trên tay như [Thuận Thủ Khiên Dương] đối với họ."},
  { name: "Khẩn Thương", desc: "Khi cần dùng [Sát], bạn có thể dùng X lá như [Sát], bạn có thể chỉ định X mục tiêu cho [Sát] này. Sau khi kết toán [Sát] này, nếu X > Y, bạn rút 1 lá (X ít nhất là 2, Y là số thiệt hại [Sát] này gây ra)."},
];

module.exports = skillDiemMac;