const skillDonThe = [
  { name: "Nhân Đức", desc: "Giai đoạn hành động giới hạn một lần với mỗi người chơi, bạn có thể đem tùy ý bài trên tay giao cho người một chơi khác. Khi bạn giao đến lá “Nhân Đức” thứ hai, bạn có thể xem như sử dụng dụng một lá Cơ Bản." },
  { name: "Nhân Tâm", desc: "Khi người chơi khác nhận sát thương, nếu số sinh lực của họ là 1, bạn có thể đặt chồng thẻ võ tướng và bỏ đi một thẻ bài Trang bị, sau đó ngăn chặn sát thương này." },
  { name: "Nhân Chính", desc: "Tỏa Định Kỹ Mỗi khi có sát thương bị giảm ít đi hoặc bị ngăn chặn, bạn rút hai thẻ bài." },
  { name: "Nghĩa Tuyệt", desc: "Giai đoạn hành động giới hạn một lần, bạn có thể bỏ đi một lá bài, sau đó lệnh một người chơi khác mở ra một lá bài trên tay: Nếu lá này màu Đen, thì họ bị vô hiệu phi tỏa định kỹ và không thể sử dụng hoặc đánh ra bài trên tay trong lượt hiện tại; bạn sử dụng [Sát] chất ♥ đối với họ gây sát thương +1.; Nếu lá này màu Đỏ, thì bạn thu lấy nó, sau đó bạn có thể lệnh người đó hồi phục 1 điểm sinh lực. Nếu lá này màu Đỏ, thì bạn thu lấy nó, sau đó bạn có thể lệnh người đó hồi phục 1 điểm sinh lực."},
  { name: "Nghĩa Tòng", desc: "Tỏa Định Kỹ Bạn tính toán cự ly đến người chơi khác -1; Nếu số sinh lực đã mất của bạn ≥ 2, người chơi khác tính toán cự ly đến bạn +1."},
  { name: "Nghĩa Xá", desc: "Giai đoạn kết thúc, nếu bạn không có “Mễ”, bạn có thể rút hai lá bài, sau đó đem hai lá bài đặt lên trên lá võ tướng, gọi là “Mễ”; Khi bạn mất đi một lá “Mễ” cuối cùng, bạn hồi phục 1 điểm sinh lực."},
  { name: "Nghĩa Tương", desc: "Tỏa Định Kỹ Trong giai đoạn hành động của người khác: Lá bài thứ nhất họ sử dụng gây sát thương -1 đối với bạn; Lá bài thứ 2 họ sử dụng là màu Đen, vô hiệu đối với bạn."},
  { name: "Cử Nghĩa", desc: "Giác Tỉnh Kỹ. Giai đoạn chuẩn bị, nếu bạn đã bị thương và giới hạn sinh lực của bạn lớn nhất bàn, bạn đem bài trên tay rút bổ sung đến bằng giới hạn sinh lực. Sau đó có được kỹ năng “Băng Hoại” và “Uy Trọng”."},
  { name: "Hào Nghĩa", desc: "Giai đoạn kết thúc, bạn có thể thu lấy bài loại gây sát thương chưa gây ra sát thương mà tiến vào chồng bài bỏ trong lượt hiện tại, đồng thời có thể phân phối cho tùy ý người chơi khác."},
  { name: "Thiên Nghĩa", desc: "Giai đoạn hành động giới hạn một lần, bạn có thể đấu điểm cùng với một người chơi:Nếu bạn thắng, bạn có thể sử dụng thêm một lá [Sát] trong lượt hiện tại, sử dụng [Sát] không hạn chế cự ly và có thể chọn thêm một mục tiêu."},
  { name: "Sùng Nghĩa", desc: "Nếu lá bài thứ nhất một người chơi sử dụng trong giai đoạn hành động là [Sát], bạn có thể lệnh họ rút hai lá bài và số lần sử dụng [Sát] trong giai đoạn này +1; Khi kết thúc giai đoạn hành động của một người chơi, nếu giai đoạn này lá cuối cũng họ sử dụng là [Sát], bạn có thể thu được [Sát] này trong chồng bài bỏ đồng thời lệnh trữ bài lượt hiện tại của họ +1."},
  { name: "Lễ Lộ", desc: "Giai đoạn rút bài, bạn có thể bỏ qua rút bài, thay đổi thành đem bài trên tay rút đến bằng giới hạn sinh lực (tối đa rút đến 5 lá), sau đó giao cho một người chơi khác ít nhất một lá bài trên tay. Nếu số bài bạn giao ra lần này lớn hơn số bài bạn giao ra một lần trước đó bằng cách này, bạn tăng 1 điểm giới hạn sinh lực và hồi phục 1 điểm sinh lực."},
  { name: "Lễ Hạ", desc: "Tỏa Định Kỹ Giai đoạn kết thúc của người chơi khác, nếu bạn không nằm trong phạm vi công kích của họ, thì bạn lựa chọn một hạng mục: Rút một lá bài; Lệnh họ rút hai lá bài. Sau khi hoàn thành lựa chọn, người chơi khác tính toán cự ly đến bạn -1."},
  { name: "Lễ Nhượng", desc: "Khi bài của bạn đi vào chồng bài bỏ do bị bỏ đi, bạn có thể đem tùy ý bài trong số đó giao cho một người chơi khác."},
  { name: "Di Lễ", desc: "Mở đầu giai đoạn hành động, bạn có thể tự mất 1 điểm sinh lực hoặc bỏ đi một “Quất”, sau đó lệnh một người chơi khác có được một “Quất”."},
  { name: "Đồng Lễ", desc: "Giai đoạn hành động, sau khi bạn sử dụng bài chỉ định mục tiêu, nếu số Chất trong bài trên tay của bạn bằng với số lá bài bạn đã sử dụng trong giai đoạn này, bạn có thể lệnh hiệu quả của bài này chấp hành thêm X lần (X là số Chất trong bài trên tay của bạn)."},
  { name: "Tập Trí", desc: "Khi bạn sử dụng bài Cẩm Nang, bạn có thể rút một lá. Nếu bài này là bài Cơ Bản, bạn có thể bỏ bài này đi sau đó giới hạn trữ bài trên tay lượt hiện tại +1."},
  { name: "Trí Trì", desc: "Tỏa Định Kỹ Sau khi bạn nhận sát thương ở ngoài lượt, lượt hiện tại [Sát] và bài Cẩm Nang thường vô hiệu đối với bạn."},
  { name: "Trí Ngu", desc: "Sau khi bạn nhận sát thương, bạn có thể rút một lá bài, sau đó mở ra tất cả bài trên tay, nếu tất cả cùng Màu, nguồn sát thương bỏ đi một lá bài trên tay."},
  { name: "Thần Trí", desc: "Giai đoạn chuẩn bị, nếu số bài trên tay của bạn > số sinh lực, bạn có thể bỏ đi một lá bài trên tay, hồi phục 1 điểm sinh lực."},
  { name: "Man Trí", desc: "Giai đoạn chuẩn bị, bạn có thể chọn một người chơi khác, sau đó chọn một hạng mục Lệnh họ giao cho bạn hai lá bài, sau đó người này xem như sử dụng 1 lá [Sát] không hạn chế cự ly. Thu tối đa hai lá bài trong khu vực của họ, sau đó giao cho họ cùng lượng bài rồi rút một lá bài. Giai đoạn kết thúc, nếu số sinh lực của bạn bằng với thời điểm giai đoạn chuẩn bị của lượt hiện tại, bạn có thể lựa chọn chấp hành hạng mục chưa được lựa chọn trong lượt hiện tại."},
  { name: "Khiển Tín", desc: "Giai đoạn hành động giới hạn một lần, nếu trong chồng bài rút không có “Tín”, bạn có thể lựa chọn một người chơi và đem tùy ý bài trên tay đặt vào vị trí bội số của X (X là số người còn sống), gọi là “Tín”. Mở đầu giai đoạn bỏ bài của người đó, nếu trong tay họ có “Tín” thu được trong lượt hiện tại, họ lựa chọn một hạng mục: Lệnh bạn đem bài trên tay bổ sung đến bốn lá; Giới hạn trữ bài lượt hiện tại -2."},

];

module.exports = skillDonThe;